export const defaults = {
  lockScale: true,
  lockedScale: "d:pentatonic",
  lockedCpm: 217,
  subSizes: [],
  subStep: 0,
  noteOffset: 6,
  highNibbleOffset: 0,
  lowNibbleOffset: 0,
  loopEnabled: true,
  leadEnabled: true,
  leadSynth: "sine",
  leadAdsr: [0.79, 0.57, 0.35, 0.19],
  leadGain: 1,
  leadLpf: 1850,
  leadHpf: 750,
  leadLpq: 7.5,
  leadShape: 0.41,
  leadBpf: 0,
  leadBpq: 0,
  leadVib: 0,
  leadDetune: 0,
  leadFm: 0,
  leadFmh: 0,
  padEnabled: true,
  padSynth: "supersaw",
  padAdsr: [0.79, 0.57, 0.87, 0.19],
  padGain: 1,
  padLpf: 1500,
  padHpf: 570,
  padLpq: 4.5,
  padShape: 0.09,
  padBpf: 0,
  padBpq: 0,
  padVib: 0,
  padDetune: 0,
  padFm: 0,
  padFmh: 0,
  droneEnabled: false,
  droneGain: 0.9,
  droneSemitones: 36,
  droneLpf: 20000,
  droneHpf: 470,
  droneLpq: 0,
  droneShape: 0,
  droneBpf: 0,
  droneBpq: 0,
  droneVib: 0,
  droneDetune: 0,
  droneFm: 0,
  droneFmh: 0,
  auxEnabled: false,
  auxSynth: "triangle",
  auxAdsr: [0.5, 1.33, 3.51, 0],
  auxGain: 1,
  auxSemitones: 12,
  auxLpf: 11750,
  auxHpf: 730,
  auxLpq: 0,
  auxShape: 0,
  auxBpf: 0,
  auxBpq: 0,
  auxVib: 7.5,
  auxDetune: 0,
  auxFm: 0,
  auxFmh: 0,
  masterRoom: 0.8,
  masterDelay: 0.34,
  midiBindings: {
    "lead-a": { cc: 73, channel: 2, deviceName: "S-1" },
    "lead-d": { cc: 75, channel: 2, deviceName: "S-1" },
    "lead-s": { cc: 30, channel: 2, deviceName: "S-1" },
    "lead-r": { cc: 72, channel: 2, deviceName: "S-1" },
    "pad-a": { cc: 73, channel: 2, deviceName: "S-1" },
    "pad-d": { cc: 75, channel: 2, deviceName: "S-1" },
    "pad-s": { cc: 30, channel: 2, deviceName: "S-1" },
    "pad-r": { cc: 72, channel: 2, deviceName: "S-1" },
    "pad-lpf": { cc: 13, channel: 2, deviceName: "S-1" },
    "pad-hpf": { cc: 75, channel: 2, deviceName: "S-1" },
    "drone-gain": { cc: 71, channel: 2, deviceName: "S-1" },
    "aux-hpf": { cc: 71, channel: 2, deviceName: "S-1" },
    "master-room": { cc: 74, channel: 2, deviceName: "S-1" },
  },
};
